<a href="https://colab.research.google.com/github/YeisonBTS/Pytorch-Introdution/blob/main/01_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
torch.__version__

'1.7.0+cu101'

In [6]:
x = torch.rand(5, 3, dtype=torch.float16)

x.dtype

torch.float16

In [10]:
x = torch.tensor([5.5, 3], dtype=torch.int)
print(x)
x.size()

tensor([5, 3], dtype=torch.int32)


torch.Size([2])

In [33]:
x = torch.tensor([5.5, 3])
y = torch.tensor([6, 4])

print(x + y)

tensor([11.5000,  7.0000])


In [34]:
print(torch.add(x, y))

tensor([11.5000,  7.0000])


In [37]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([11.5000,  7.0000])


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: An output with one or more elements was resized since it had shape [5, 3], which does not match the required output shape [2].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  /pytorch/aten/src/ATen/native/Resize.cpp:19.)
  


In [20]:
# adds x to y
y.add_(x)
print(y)

tensor([44., 24.])


In [27]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
 

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [45]:
x = torch.randn(1)
print(x)
x.item()

tensor([1.8458])


1.845821738243103

In [61]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

y = x + 2
y

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [62]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [63]:
print(x.grad)


None


In [64]:
out.backward()

In [65]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [66]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([1269.4482,  580.8050, -779.3524], grad_fn=<MulBackward0>)
